steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://function-data/env/dev.yaml', '.']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://core-350507-function-data/env/prod.yaml', '.']
- name: 'bash'
  args: ['./deploy.sh','${TAG_NAME}']
- name: gcr.io/cloud-builders/gcloud:latest
  entrypoint: "ls"
  args: ["-lah","/workspace"]

options:
  logging: CLOUD_LOGGING_ONLY