steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - '-c'
  - |
    version=( $(grep -Eo '[[:digit:]]+|[^[:digit:]]+' <<<'$BRANCH_NAME') )
    echo ${version}
    gcloud \
    functions \
    deploy \
    enrich-vat \
    --region=europe-west1 \
    --source=./enrichVatCode \
    --trigger-http \
    --runtime=go116 \
    --entry-point=EnrichVatCode \
    --service-account=146852404745@cloudbuild.gserviceaccount.com \
    --set-env-vars "^##^MUNICHREBASEURL=$_MUNICHREBASEURL,MUNICHREBASEURL=$_MUNICHREBASEURL"
    --project=positive-apex-350507 
  entrypoint: bash