steps:
- name: gcr.io/cloud-builders/gsutil
  id: 'Load env variables'
  env:
    - '_ENV=$_ENV'
    - '_PRIVATE_BUCKET_NAME=$_PRIVATE_BUCKET_NAME'
  args: [
    'cp',
    'gs://${_PRIVATE_BUCKET_NAME}/env/${_ENV}.yaml',
    '.'
  ]
- name: gcr.io/cloud-builders/gcloud:latest
  id: 'Deploy'
  entrypoint: 'bash'
  waitFor:
    - 'Load env variables'
  args:
  - '-c'
  - | 
    # === EXTRACT FUNCTION NAME AND VERSION FROM TAG ===========================
    # Read TAG_NAME splitting by the IFS separator into the needed variables
    IFS='/'
    read -a strarr <<< $TAG_NAME
    fx_name=$(echo ${strarr[0]})
    tag=$(echo ${strarr[1]})
    echo "fx_name: ${fx_name}"
    echo "tag: ${tag}"

    # === FX ENTRYPOINT AND TAG VERSION ========================================
    # Camel case function entrypoint. Ex.: broker -> Broker 
    fx_entrypoint=$(sed -r 's/(^|-)(\w)/\U\2/g' <<<"${fx_name}")
    # Replace '.' with '_' for tag version. Ex.: 1.2.3.dev -> 1_2_3_dev 
    tag_version=$(echo "${tag}" | sed -r 's/\./_/g')
    echo "fx_entrypoint: ${fx_entrypoint}"
    echo "tag_version: ${tag_version}"

    chmod +x ./deploy-envs.sh
    ./deploy-envs.sh ${TAG_NAME}

options:
  logging: CLOUD_LOGGING_ONLY
