#!/bin/bash
export FUNCTION_TARGET="Document"
export FUNCTION_TARGET="AppcheckProxy"
export FUNCTION_TARGET="Rules"
export FUNCTION_TARGET="Quote"
export FUNCTION_TARGET="Mail"
export FUNCTION_TARGET="Document"
export FUNCTION_TARGET="Enrich"
export FUNCTION_TARGET="Claim"
export FUNCTION_TARGET="Form"
export FUNCTION_TARGET="Product"
export FUNCTION_TARGET="User"
export FUNCTION_TARGET="WiseProxy"
export FUNCTION_TARGET="Broker"