steps:
- name: 'gcr.io/cloud-builders/gcloud:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # === EXTRACT MODULE NAME AND VERSION FROM TAG =================================
    # Read TAG_NAME splitting by the IFS separator into the needed variables
    IFS='/'
    read -a TAG_ARRAY <<< $TAG_NAME

    gcloud artifacts go upload --project=${PROJECT_ID} \
      --repository=${_REPOSITORY} \
      --location=${_REGION} \
      --module-path=${_MODULE_PREFIX}/${TAG_ARRAY[0]} \
      --version=${TAG_ARRAY[1]} \
      --source=/workspace/${TAG_ARRAY[0]}

options:
  logging: CLOUD_LOGGING_ONLY
