steps:
- name: 'golang:1.23'
  entrypoint: go
  dir: '.cloudbuild/go_scripts'
  env:
    - 'GIT_REMOTE=$_GIT_REMOTE'
  args:
    - run
    - main.go
    - '--script=tag_modules'
    - '--modules=$_MODULES'
    - '--modulePath=$_MODULE_PATH'

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_NUMBER_DEPLOY/secrets/GITLAB_GOWORKSPACE_ACCESS_TOKEN/versions/1
      env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
