steps:
- name: 'golang:1.23'
  entrypoint: go
  dir: '.cloudbuild/go_scripts'
  env:
    - 'GIT_REMOTE=$_GIT_REMOTE'
  secretEnv:
    - 'GIT_ACCESS_TOKEN'
  args:
    - run
    - main.go
    - '--script=tag_functions'
    - '--functions=$_FUNCTIONS'
    - '--from=$_FROM_ENV'
    - '--target=$_TARGET_ENV'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/GITLAB_GOWORKSPACE_ACCESS_TOKEN/versions/1
      env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
