package user

var foreignCountries = map[string]map[string]string{
	"grenada": {
		"codFisc":  "Z524",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"isola di man": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z122",
	},
	"maldive": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z232",
	},
	"paraguay": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z610",
	},
	"sudan": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z348",
	},
	"cuba": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z504",
	},
	"guyana": {
		"codFisc":  "Z606",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"bahamas": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z502",
		"cap":      "",
	},
	"lussemburgo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z120",
	},
	"mongolia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z233",
	},
	"qatar": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z237",
	},
	"sri lanka": {
		"codFisc":  "Z209",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"tanzania": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z357",
	},
	"brunei darussalam": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z207",
	},
	"saint pierre e miquelon": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z403",
	},
	"sint maarten (nl)": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z126",
	},
	"moldova": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z140",
	},
	"canada": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z401",
	},
	"isole cook (nz)": {
		"province": "EE",
		"codFisc":  "Z703",
		"cap":      "",
		"region":   "",
	},
	"laos": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z228",
	},
	"oman": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z235",
	},
	"turchia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z243",
	},
	"burundi": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z305",
	},
	"islanda": {
		"province": "EE",
		"codFisc":  "Z117",
		"cap":      "",
		"region":   "",
	},
	"myanmar/birmania": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z206",
	},
	"terre australi e antartiche francesi": {
		"province": "EE",
		"codFisc":  "Z110",
		"cap":      "",
		"region":   "",
	},
	"haiti": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z510",
	},
	"el salvador": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z506",
	},
	"belize": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z512",
		"cap":      "",
	},
	"finlandia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z109",
	},
	"ruanda": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z338",
	},
	"angola": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z302",
	},
	"kirghizistan": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z256",
	},
	"montenegro": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z159",
	},
	"guinea equatoriale": {
		"codFisc":  "Z321",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"serbia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z158",
	},
	"tonga": {
		"province": "EE",
		"codFisc":  "Z728",
		"cap":      "",
		"region":   "",
	},
	"egitto": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z336",
	},
	"yemen": {
		"codFisc":  "Z246",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"barbados": {
		"codFisc":  "Z522",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"liberia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z325",
	},
	"per�": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z611",
	},
	"seychelles": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z342",
	},
	"antigua e barbuda": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z532",
		"cap":      "",
	},
	"somalia": {
		"codFisc":  "Z345",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"cile": {
		"codFisc":  "Z603",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"georgia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z254",
	},
	"giappone": {
		"codFisc":  "Z219",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"corea del nord": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z214",
	},
	"kazakhstan": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z255",
	},
	"lettonia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z145",
	},
	"norvegia": {
		"codFisc":  "Z125",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"corea del sud": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z213",
		"cap":      "",
	},
	"colombia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z604",
	},
	"ghana": {
		"codFisc":  "Z318",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"polonia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z127",
	},
	"regno unito": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z114",
	},
	"sahara occidentale": {
		"province": "EE",
		"codFisc":  "Z339",
		"cap":      "",
		"region":   "",
	},
	"suriname": {
		"codFisc":  "Z608",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"zambia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z355",
	},
	"andorra": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z101",
	},
	"germania": {
		"codFisc":  "Z112",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"zimbabwe": {
		"province": "EE",
		"codFisc":  "Z337",
		"cap":      "",
		"region":   "",
	},
	"bangladesh": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z249",
	},
	"filippine": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z216",
	},
	"burkina faso": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z354",
	},
	"cambogia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z208",
	},
	"dominica": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z526",
		"cap":      "",
	},
	"estonia": {
		"province": "EE",
		"codFisc":  "Z144",
		"cap":      "",
		"region":   "",
	},
	"guinea-bissau": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z320",
		"cap":      "",
	},
	"isole marshall": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z711",
	},
	"malawi": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z328",
	},
	"repubblica dominicana": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z505",
		"cap":      "",
	},
	"cina": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z210",
	},
	"namibia": {
		"codFisc":  "Z300",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"timor leste": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z242",
	},
	"armenia": {
		"codFisc":  "Z252",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"capo verde": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z307",
	},
	"guatemala": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z509",
	},
	"kenya": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z322",
	},
	"pakistan": {
		"codFisc":  "Z236",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"sud sudan": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z907",
	},
	"comune": {
		"cap":      "",
		"region":   "",
		"province": "Provincia",
		"codFisc":  "CodFisco",
	},
	"svezia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z132",
	},
	"romania": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z129",
		"cap":      "",
	},
	"figi": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z704",
	},
	"isole f�r �er": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z108",
		"cap":      "",
	},
	"malta": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z121",
	},
	"nigeria": {
		"codFisc":  "Z335",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"camerun": {
		"province": "EE",
		"codFisc":  "Z306",
		"cap":      "",
		"region":   "",
	},
	"mauritania": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z331",
	},
	"mozambico": {
		"province": "EE",
		"codFisc":  "Z333",
		"cap":      "",
		"region":   "",
	},
	"panama": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z516",
		"cap":      "",
	},
	"venezuela": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z614",
	},
	"india": {
		"codFisc":  "Z222",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"bermuda": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z400",
	},
	"isole cayman": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z530",
	},
	"kosovo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z160",
	},
	"liechtenstein": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z119",
	},
	"lituania": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z146",
	},
	"belgio": {
		"province": "EE",
		"codFisc":  "Z103",
		"cap":      "",
		"region":   "",
	},
	"etiopia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z315",
	},
	"messico": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z514",
	},
	"monaco": {
		"codFisc":  "Z123",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"saint vincent e grenadine": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z528",
	},
	"sark": {
		"codFisc":  "Z114",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"thailandia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z241",
	},
	"brasile": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z602",
		"cap":      "",
	},
	"israele": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z226",
	},
	"repubblica democratica del congo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z312",
	},
	"indonesia": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z223",
		"cap":      "",
	},
	"portogallo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z128",
	},
	"uzbekistan": {
		"codFisc":  "Z259",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"irlanda": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z116",
	},
	"samoa": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z726",
	},
	"sao tom� e principe": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z341",
	},
	"slovenia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z150",
	},
	"tuvalu": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z732",
	},
	"arabia saudita": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z203",
	},
	"eritrea": {
		"province": "EE",
		"codFisc":  "Z368",
		"cap":      "",
		"region":   "",
	},
	"isole falkland (malvine)": {
		"codFisc":  "Z609",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"isole salomone": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z724",
		"cap":      "",
	},
	"togo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z351",
	},
	"tunisia": {
		"codFisc":  "Z352",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"bulgaria": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z104",
		"cap":      "",
	},
	"croazia": {
		"province": "EE",
		"codFisc":  "Z149",
		"cap":      "",
		"region":   "",
	},
	"gambia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z317",
	},
	"repubblica ceca": {
		"codFisc":  "Z156",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"bhutan": {
		"province": "EE",
		"codFisc":  "Z205",
		"cap":      "",
		"region":   "",
	},
	"saint kitts e nevis": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z533",
	},
	"senegal": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z343",
	},
	"botswana": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z358",
	},
	"malaysia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z247",
	},
	"san marino": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z130",
	},
	"kuwait": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z227",
	},
	"lesotho": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z359",
	},
	"nuova caledonia": {
		"province": "EE",
		"codFisc":  "Z716",
		"cap":      "",
		"region":   "",
	},
	"polinesia francese": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z723",
	},
	"danimarca": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z107",
	},
	"costa rica": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z503",
	},
	"papua nuova guinea": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z730",
	},
	"singapore": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z248",
	},
	"svizzera": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z133",
	},
	"austria": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z102",
		"cap":      "",
	},
	"gabon": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z316",
	},
	"grecia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z115",
	},
	"maurizio": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z332",
		"cap":      "",
	},
	"stati uniti d'america": {
		"province": "EE",
		"codFisc":  "Z404",
		"cap":      "",
		"region":   "",
	},
	"ungheria": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z134",
	},
	"bosnia-erzegovina": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z153",
	},
	"gibilterra": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z113",
	},
	"isole pitcairn": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z722",
	},
	"stati federati di micronesia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z735",
	},
	"comore": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z310",
	},
	"federazione russa": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z154",
	},
	"libia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z326",
	},
	"macedonia del nord": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z148",
	},
	"sudafrica": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z347",
	},
	"emirati arabi uniti": {
		"province": "EE",
		"codFisc":  "Z215",
		"cap":      "",
		"region":   "",
	},
	"gibuti": {
		"province": "EE",
		"codFisc":  "Z361",
		"cap":      "",
		"region":   "",
	},
	"isole turks e caicos": {
		"codFisc":  "Z519",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"palau": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z734",
	},
	"sierra leone": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z344",
	},
	"francia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z110",
	},
	"ecuador": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z605",
	},
	"turkmenistan": {
		"province": "EE",
		"codFisc":  "Z258",
		"cap":      "",
		"region":   "",
	},
	"algeria": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z301",
	},
	"marocco": {
		"codFisc":  "Z330",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"saint-martin (fr)": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z110",
	},
	"benin": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z314",
	},
	"nicaragua": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z515",
	},
	"cura�ao": {
		"codFisc":  "Z126",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"vanuatu": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z733",
	},
	"nuova zelanda": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z719",
	},
	"groenlandia": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z402",
		"cap":      "",
	},
	"guinea": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z319",
	},
	"honduras": {
		"codFisc":  "Z511",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"mali": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z329",
	},
	"repubblica centrafricana": {
		"codFisc":  "Z308",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"sant'elena": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z340",
	},
	"trinidad e tobago": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z612",
	},
	"azerbaigian": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z253",
	},
	"jersey": {
		"province": "EE",
		"codFisc":  "Z114",
		"cap":      "",
		"region":   "",
	},
	"giamaica": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z507",
	},
	"libano": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z229",
		"cap":      "",
	},
	"madagascar": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z327",
	},
	"nepal": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z234",
		"cap":      "",
	},
	"kiribati": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z731",
	},
	"vietnam": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z251",
	},
	"afghanistan": {
		"codFisc":  "Z200",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"albania": {
		"province": "EE",
		"codFisc":  "Z100",
		"cap":      "",
		"region":   "",
	},
	"santa lucia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z527",
	},
	"guernsey": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z114",
	},
	"isole vergini britanniche": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z525",
		"cap":      "",
	},
	"saint-barth�lemy": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z110",
	},
	"costa d'avorio": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z313",
	},
	"slovacchia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z155",
	},
	"taiwan": {
		"region":   "",
		"province": "EE",
		"codFisc":  "Z217",
		"cap":      "",
	},
	"bielorussia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z139",
	},
	"ciad": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z309",
	},
	"giordania": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z220",
	},
	"spagna": {
		"province": "EE",
		"codFisc":  "Z131",
		"cap":      "",
		"region":   "",
	},
	"bolivia": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z601",
	},
	"stato della citt� del vaticano": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z106",
	},
	"australia": {
		"province": "EE",
		"codFisc":  "Z700",
		"cap":      "",
		"region":   "",
	},
	"eswatini": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z349",
	},
	"niger": {
		"codFisc":  "Z334",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"paesi bassi": {
		"codFisc":  "Z126",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"anguilla": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z529",
	},
	"tagikistan": {
		"province": "EE",
		"codFisc":  "Z257",
		"cap":      "",
		"region":   "",
	},
	"uruguay": {
		"codFisc":  "Z613",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"palestina": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z161",
	},
	"cipro": {
		"codFisc":  "Z211",
		"cap":      "",
		"region":   "",
		"province": "EE",
	},
	"nauru": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z713",
	},
	"argentina": {
		"province": "EE",
		"codFisc":  "Z600",
		"cap":      "",
		"region":   "",
	},
	"uganda": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z353",
	},
	"aruba": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z501",
	},
	"iran": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z224",
	},
	"montserrat": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z531",
	},
	"wallis e futuna": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z729",
	},
	"congo": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z311",
	},
	"siria": {
		"province": "EE",
		"codFisc":  "Z240",
		"cap":      "",
		"region":   "",
	},
	"bahrein": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z204",
	},
	"ucraina": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z138",
	},
	"iraq": {
		"cap":      "",
		"region":   "",
		"province": "EE",
		"codFisc":  "Z225",
	},
}
