name: GoWorkspace - Run Test
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - '**/*.go'

env:
  ENV: 'local-test'

jobs:
  run_test:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.7'

      - name: Go Version
        run: go version

      - name: Authenticate to Google Cloud
        id: authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Clone function-data
        run: |
          pwd
          gcloud source repos clone fuction-data ../function-data --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Run Tests
        run: go test github.com/wopta/goworkspace/...

      - name: Clean up
        run: |
          rm -f key.json
