name: GoWorkspace - Run Test
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - '*/*.go'
jobs:
  run_test:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.7' # The Go version to download (if necessary) and use.

      - name: Go Version
        run: go version

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        id: authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Save GCP credentials to file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: echo "$GCP_SA_KEY" > ${{ runner.temp }}/key.json

      - name: Activate service account
        run: |
          gcloud auth activate-service-account --key-file=${{ runner.temp }}/key.json
          gcloud config set account $(gcloud auth list --filter=status:ACTIVE --format="value(account)")
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Clone function-data
        run: |
          pwd
          gcloud source repos clone fuction-data ../function-data --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Set env
        run: echo "ENV=local-test" >> $GITHUB_ENV

      - name: Run Tests
        run: go test github.com/wopta/goworkspace/...

      - name: Clean up
        run: |
          rm -f key.json
